    - name: install mysql libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - cryptography
        - PyMySQL

    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: connect to mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: localhost
      register: mysql_info
      ignore_errors: true

    - name: print the output
      ansible.builtin.debug:
        msg: "MYSQL info : {{ mysql_info }}"

    - name: secure mysql installation (if failed)
      ansible.builtin.command: >
        mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"
      when: mysql_info.failed